# Generated by Django 2.2.4 on 2019-08-08 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('female', models.BooleanField()),
                ('registered_on', models.DateTimeField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('registered_on', models.DateTimeField(blank=True, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Author')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('publish_year', models.IntegerField()),
                ('registered_on', models.DateTimeField(blank=True, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Author')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Series')),
            ],
        ),
        migrations.CreateModel(
            name='ai',
            fields=[
                ('ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='')),
                ('gender', models.CharField(choices=[('1', 'X'), ('2', 'XX'), ('3', 'XXX'), ('4', 'XXXX'), ('5', 'XXXXX')], max_length=1)),
                ('short_name', models.CharField(max_length=10)),
                ('manifestation', models.TextField()),
                ('physical', models.CharField(choices=[('1', 'X'), ('2', 'XX'), ('3', 'XXX'), ('4', 'XXXX'), ('5', 'XXXXX')], max_length=1)),
                ('difference', models.TextField()),
                ('technical', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('consciousness', models.CharField(choices=[('1', 'X'), ('2', 'XX'), ('3', 'XXX'), ('4', 'XXXX'), ('5', 'XXXXX')], max_length=1)),
                ('intelligence', models.CharField(choices=[('1', 'X'), ('2', 'XX'), ('3', 'XXX'), ('4', 'XXXX')], max_length=1)),
                ('free_will', models.BooleanField()),
                ('learning', models.BooleanField()),
                ('emotional', models.BooleanField()),
                ('integration', models.CharField(choices=[('1', 'X'), ('2', 'XX'), ('3', 'XXX'), ('4', 'XXXX')], max_length=1)),
                ('on_purpose', models.BooleanField()),
                ('creator_rel', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('owner_rel', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('female_creator', models.BooleanField()),
                ('society_pos', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('subject', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('servant', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('intimacy', models.CharField(choices=[('1', 'X'), ('2', 'XX'), ('3', 'XXX'), ('4', 'XXXX')], max_length=1)),
                ('told_by', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('warrior', models.BooleanField()),
                ('rebellious', models.BooleanField()),
                ('harmed_humans', models.BooleanField()),
                ('harms_creator', models.BooleanField()),
                ('more_control', models.BooleanField()),
                ('world_domination', models.BooleanField()),
                ('alien_technology', models.BooleanField()),
                ('explicit_mention', models.BooleanField()),
                ('registered_on', models.DateTimeField(blank=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Book')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
