# Generated by Django 2.2.4 on 2019-09-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidatabase', '0002_auto_20190922_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='author_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='ai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Ai'),
        ),
    ]
