# Generated by Django 2.2.4 on 2019-09-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidatabase', '0005_auto_20190922_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='add_information',
            field=models.TextField(blank=True, null=True, verbose_name='Some Additional Information'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Ai'),
        ),
    ]
