# Generated by Django 2.2.4 on 2019-09-28 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidatabase', '0006_auto_20190922_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_type', models.CharField(choices=[('NL', 'novel'), ('CO', 'comic'), ('MG', 'manga'), ('FM', 'film'), ('SE', 'series'), ('AN', 'anime'), ('GM', 'game'), ('NA', 'novella'), ('SS', 'shortstory'), ('MZ', 'magazine'), ('OT', 'other')], max_length=2)),
                ('object_id', models.PositiveIntegerField()),
                ('publish_year', models.IntegerField()),
                ('registered_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ai',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='registered_on',
        ),
        migrations.RemoveField(
            model_name='book',
            name='series_id',
        ),
        migrations.AlterField(
            model_name='author',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='ai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Ai'),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AddField(
            model_name='ai',
            name='origin_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Origin'),
            preserve_default=False,
        ),
    ]
