# Generated by Django 2.2.4 on 2019-09-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidatabase', '0007_auto_20190928_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='ai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Ai'),
        ),
    ]
