# Generated by Django 2.2.4 on 2019-09-28 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidatabase', '0008_auto_20190928_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('medium_type', models.CharField(choices=[('NL', 'novel'), ('CO', 'comic'), ('MG', 'manga'), ('FM', 'film'), ('SE', 'series'), ('AN', 'anime'), ('GM', 'game'), ('NA', 'novella'), ('SS', 'shortstory'), ('MZ', 'magazine'), ('OT', 'other')], max_length=2)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_year', models.IntegerField()),
                ('website', models.URLField(blank=True)),
                ('title', models.CharField(max_length=30)),
                ('registered_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='firstname', max_length=30, verbose_name='firstname')),
                ('lastname', models.CharField(default='lastname', max_length=30, verbose_name='lastname')),
                ('female', models.BooleanField()),
                ('website', models.URLField(blank=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_information', models.TextField(blank=True, null=True, verbose_name='Some Additional Information')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='origin',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='ai',
            name='origin_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='rev_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='written', to='aidatabase.Person'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Ai'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
        migrations.AddField(
            model_name='ai',
            name='medium_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Medium'),
        ),
    ]
