# Generated by Django 2.2.4 on 2019-09-28 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidatabase', '0010_auto_20190928_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('medium_type', models.CharField(choices=[('NL', 'novel'), ('CO', 'comic'), ('MG', 'manga'), ('FM', 'film'), ('SE', 'series'), ('AN', 'anime'), ('GM', 'game'), ('NA', 'novella'), ('SS', 'shortstory'), ('MZ', 'magazine'), ('OT', 'other')], max_length=2)),
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_year', models.IntegerField(verbose_name='first published')),
                ('website', models.URLField(blank=True)),
                ('title', models.CharField(max_length=60)),
                ('registered_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ManyToManyField(blank=True, related_name='created', to='aidatabase.Person')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='medium',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='medium',
            name='registered_by',
        ),
        migrations.RemoveField(
            model_name='ai',
            name='medium_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='ai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Ai'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Medium',
        ),
        migrations.AddField(
            model_name='ai',
            name='source_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='aidatabase.Source'),
        ),
    ]
